[#runtime-types-installation]
= Installation

Um Deepkit's Runtime Typessystem zu installieren werden zwei Pakete benötigt. Der Typen-Compiler in `@deepkit/type-compiler` und die dazu nötige Runtime in `@deepkit/type`. Der Typen-Compiler kann dabei in `package.json` _devDependencies_ installiert werden, da er nur zur Build-Zeit benötigt wird.

```
npm install --save @deepkit/type
npm install --save-dev @deepkit/type-compiler
```

Laufzeit Typeninformationen werden standardmäßig nicht generiert. Es muss `"reflection": true` in der Datei `tsconfig.json` gesetzt werden, um es in allen Dateien im gleichen Ordner dieser Datei oder in allen Unterordnern zu aktivieren. Wenn Decorators verwenden werden sollen, muss `"experimentalDecorators": true` in der `tsconfig.json` aktiviert werden. Dies ist nicht unbedingt erforderlich, um mit `@deepkit/type` zu arbeiten, aber für bestimmte Funktionen anderen Deepkit Libraries und in `@deepkit/framework` notwendig.

_Datei: tsconfig.json_

```json
{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "es6",
    "moduleResolution": "node",
    "experimentalDecorators": true
  },
  "reflection": true
}
```

== Type compiler

//not sure how to write that
TypeScript selbst erlaubt es nicht, den Typen-Compiler über eine `tsconfig.json` zu konfigurieren. Es ist entweder nötig, die TypeScript Compiler API direkt oder ein Build-System wie Webpack mit _ts-loader_ zu benutzen. Um diesen unangenehmen Weg den Benutzern von Deepkit zu ersparen, installiert sich der Deepkit Typen-Compiler automatisch selbst in `node_modules/typescript` sobald `@deepkit/type-compiler` installiert wird (dies geschieht über NPM install hooks).
Dies macht es möglich, dass alle Buildtools, die auf das lokal installierte TypeScript (das in `node_modules/typescript`) zugreifen, automatisch den Typen-Compiler aktiviert haben. Dadurch funktioniert _tsc_, Angular, webpack, _ts-node_, und einige andere Tools automatisch mit dem Deepkit Typen-Compiler.

Falls der Typen-Compiler nicht erfolgreich automatisch installiert werden konnte (weil zum Beispiel NPM install hooks deaktiviert sind), kann dies manuell mit folgendem Kommando nachgeholt werden:

```sh
node_modules/.bin/deepkit-type-install
```

Beachten Sie, dass `deepkit-type-install` ausführt werden muss, wenn die lokale Typescript-Version aktualisiert wurde (zum Beispiel, wenn sich die Typescript-Version in package.json geändert hat und `npm install` ausgeführt wird).

== Webpack

Wenn der Typen-Compiler in einem Webpack-Build verwenden werden solle, kann dies mit dem Paket `ts-loader` (oder jedem anderen Typescript-Loader, der die Registrierung von Transformatoren unterstützt) tun.

_Datei: webpack.config.js_

```javascript
const typeCompiler = require('@deepkit/type-compiler');

module.exports = {
  entry: './app.ts',
  module: {
    rules: [
      {
        test: /\.tsx?$/,
          use: {
            loader: 'ts-loader',
            options: {
              //this enables @deepkit/type's type compiler
              getCustomTransformers: (program, getProgram) => ({
                before: [typeCompiler.transformer],
                afterDeclarations: [typeCompiler.declarationTransformer],
              }),
            }
          },
          exclude: /node_modules/,
       },
    ],
  },
}
```
